const { Pool } = require('pg');
const bcrypt = require('bcryptjs');

const pool = new Pool(
  process.env.DATABASE_URL
    ? {
        connectionString: process.env.DATABASE_URL,
        ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : undefined
      }
    : {
        host: process.env.PGHOST || 'localhost',
        port: Number(process.env.PGPORT) || 5432,
        database: process.env.PGDATABASE || 'sport_coach_app',
        user: process.env.PGUSER || 'postgres',
        password: process.env.PGPASSWORD || ''
      }
);

const normalizeQuery = (sql, params = []) => {
  let index = 0;
  const text = sql.replace(/\?/g, () => `$${++index}`);
  return { text, values: params };
};

const query = async (sql, params = []) => {
  const normalized = normalizeQuery(sql, params);
  return pool.query(normalized.text, normalized.values);
};

const get = async (sql, ...params) => {
  const result = await query(sql, params);
  return result.rows[0] || null;
};

const all = async (sql, ...params) => {
  const result = await query(sql, params);
  return result.rows;
};

const run = async (sql, ...params) => {
  const result = await query(sql, params);
  return {
    rowCount: result.rowCount,
    changes: result.rowCount,
    rows: result.rows
  };
};

const transaction = async (callback) => {
  const client = await pool.connect();
  const tx = {
    query: async (sql, params = []) => {
      const normalized = normalizeQuery(sql, params);
      return client.query(normalized.text, normalized.values);
    },
    get: async (sql, ...params) => {
      const result = await tx.query(sql, params);
      return result.rows[0] || null;
    },
    all: async (sql, ...params) => {
      const result = await tx.query(sql, params);
      return result.rows;
    },
    run: async (sql, ...params) => {
      const result = await tx.query(sql, params);
      return {
        rowCount: result.rowCount,
        changes: result.rowCount,
        rows: result.rows
      };
    }
  };

  try {
    await client.query('BEGIN');
    const value = await callback(tx);
    await client.query('COMMIT');
    return value;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
};

const initDatabase = async () => {
  await query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      name TEXT NOT NULL,
      first_name TEXT,
      last_name TEXT,
      birth_date TEXT,
      role TEXT DEFAULT 'user' NOT NULL,
      password_set BOOLEAN DEFAULT FALSE NOT NULL,
      age INTEGER,
      weight REAL,
      phone TEXT,
      offer_type TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS programs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      description TEXT,
      session_minutes INTEGER DEFAULT 20,
      session_volume_value REAL,
      session_volume_unit TEXT DEFAULT 'minutes',
      banner_image TEXT,
      coach_notes TEXT
    );

    CREATE TABLE IF NOT EXISTS workouts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      program_id INTEGER NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
      week INTEGER NOT NULL,
      day INTEGER NOT NULL,
      name TEXT NOT NULL,
      duration_minutes INTEGER DEFAULT 0,
      volume_value REAL,
      volume_unit TEXT DEFAULT 'minutes',
      description TEXT
    );

    CREATE TABLE IF NOT EXISTS program_assignments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      program_id INTEGER NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      scheduled_date TEXT NOT NULL,
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      notes TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS daily_checkins (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      checkin_date TEXT NOT NULL,
      mood INTEGER NOT NULL,
      energy INTEGER NOT NULL,
      sleep_quality INTEGER NOT NULL,
      stress INTEGER DEFAULT 3,
      notes TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, checkin_date)
    );

    CREATE TABLE IF NOT EXISTS assignment_feedback (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      assignment_id INTEGER NOT NULL REFERENCES program_assignments(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      difficulty INTEGER NOT NULL,
      pain_notes TEXT,
      comments TEXT,
      duration_minutes INTEGER DEFAULT 0,
      completed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(assignment_id, user_id)
    );
  `);

  await query(`
    ALTER TABLE users
    ADD COLUMN IF NOT EXISTS offer_type TEXT
  `);

  await query(`
    ALTER TABLE programs
    ADD COLUMN IF NOT EXISTS session_volume_value REAL
  `);

  await query(`
    ALTER TABLE programs
    ADD COLUMN IF NOT EXISTS session_volume_unit TEXT DEFAULT 'minutes'
  `);

  await query(`
    ALTER TABLE workouts
    ADD COLUMN IF NOT EXISTS volume_value REAL
  `);

  await query(`
    ALTER TABLE workouts
    ADD COLUMN IF NOT EXISTS volume_unit TEXT DEFAULT 'minutes'
  `);

  await query(`
    UPDATE workouts
    SET
      volume_value = COALESCE(volume_value, NULLIF(duration_minutes, 0)::REAL),
      volume_unit = COALESCE(NULLIF(volume_unit, ''), 'minutes')
  `);

  await query(`
    UPDATE programs
    SET
      session_minutes = COALESCE(session_minutes, 20),
      session_volume_value = COALESCE(session_volume_value, session_minutes::REAL),
      session_volume_unit = COALESCE(NULLIF(session_volume_unit, ''), 'minutes'),
      category = COALESCE(NULLIF(category, ''), 'Course à pied'),
      coach_notes = COALESCE(coach_notes, '')
  `);

  await query(`
    UPDATE users
    SET
      first_name = COALESCE(first_name, split_part(name, ' ', 1)),
      last_name = COALESCE(last_name, NULLIF(trim(substr(name, length(split_part(name, ' ', 1)) + 1)), ''))
  `);

  await query(`
    UPDATE daily_checkins
    SET stress = COALESCE(stress, GREATEST(1, LEAST(5, ROUND(((6 - mood) + (6 - energy)) / 2.0)::INTEGER)))
  `);

  const programCount = await get('SELECT COUNT(*)::INTEGER as count FROM programs');
  if (programCount.count === 0) {
    await transaction(async (tx) => {
      const program1 = await tx.get(`
        INSERT INTO programs (name, category, description, session_minutes, coach_notes)
        VALUES (?, ?, ?, ?, ?)
        RETURNING id
      `,
        'Débutant Force',
        'Renforcement',
        'Programme de musculation pour débutants visant à développer la force de base.',
        45,
        'Conserver 90 secondes de récupération entre les blocs.'
      );

      const workouts1 = [
        { week: 1, day: 1, name: 'Push', description: 'Entraînement push pour le haut du corps' },
        { week: 1, day: 2, name: 'Pull', description: 'Entraînement pull pour le dos' },
        { week: 2, day: 1, name: 'Push Avancé', description: 'Push avec plus d\'intensité' },
        { week: 2, day: 2, name: 'Pull Avancé', description: 'Pull avec plus d\'intensité' }
      ];

      for (const workout of workouts1) {
        await tx.run(`
          INSERT INTO workouts (program_id, week, day, name, description)
          VALUES (?, ?, ?, ?, ?)
        `, program1.id, workout.week, workout.day, workout.name, workout.description);
      }

      const program2 = await tx.get(`
        INSERT INTO programs (name, category, description, session_minutes, coach_notes)
        VALUES (?, ?, ?, ?, ?)
        RETURNING id
      `,
        'Cardio Débutant',
        'Course à pied',
        'Programme cardio pour débutants axé sur la perte de poids.',
        30,
        'Commencer en aisance respiratoire avant de monter en intensité.'
      );

      const workouts2 = [
        { week: 1, day: 1, name: 'Course Léger', description: 'Course légère pour commencer' },
        { week: 1, day: 2, name: 'Marche Rapide', description: 'Marche rapide avec intervalles' },
        { week: 2, day: 1, name: 'Course Moyenne', description: 'Course avec plus d\'intensité' },
        { week: 2, day: 2, name: 'HIIT Débutant', description: 'Entraînement par intervalles' }
      ];

      for (const workout of workouts2) {
        await tx.run(`
          INSERT INTO workouts (program_id, week, day, name, description)
          VALUES (?, ?, ?, ?, ?)
        `, program2.id, workout.week, workout.day, workout.name, workout.description);
      }
    });
  }

  const adminCount = await get('SELECT COUNT(*)::INTEGER as count FROM users WHERE role = ?', 'admin');
  if (adminCount.count === 0) {
    const hashedPassword = await bcrypt.hash('admin123', 10);
    await run(`
      INSERT INTO users (email, password_hash, name, role, password_set)
      VALUES (?, ?, ?, ?, TRUE)
    `, 'admin@admin.com', hashedPassword, 'Administratrice', 'admin');
  }
};

module.exports = {
  pool,
  query,
  get,
  all,
  run,
  transaction,
  initDatabase
};
